[project]
name = "example-reader-step"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    # needed for logging in AzureML
    "azureml-mlflow==1.60.*",
    "mlflow-skinny==2.21.*",
    "pytz==2025.2",
]

[project.scripts]
example-reader-step = "example_reader_step.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
